spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deliveries
    username: deliveries
    password: deliveries
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    com.delivery.optimizer: DEBUG
